// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAHwXEGUKachQoVNnjHAtv2lFgoNJEMmc',
    appId: '1:186129183743:web:7d38f76be89429c4df6dca',
    messagingSenderId: '186129183743',
    projectId: 'agora-live-streaming-10',
    authDomain: 'agora-live-streaming-10.firebaseapp.com',
    storageBucket: 'agora-live-streaming-10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCqz-s9Ju_Zm_B9bCTyIqjhDEsAwliZmU',
    appId: '1:186129183743:android:fc436b48939c5da6df6dca',
    messagingSenderId: '186129183743',
    projectId: 'agora-live-streaming-10',
    storageBucket: 'agora-live-streaming-10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDJT9m0TM5-M9__oGl2kY-gVnUWTjSmTg',
    appId: '1:186129183743:ios:36f5baa3750d3b1edf6dca',
    messagingSenderId: '186129183743',
    projectId: 'agora-live-streaming-10',
    storageBucket: 'agora-live-streaming-10.firebasestorage.app',
    iosBundleId: 'com.example.agoraLiveStream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDJT9m0TM5-M9__oGl2kY-gVnUWTjSmTg',
    appId: '1:186129183743:ios:36f5baa3750d3b1edf6dca',
    messagingSenderId: '186129183743',
    projectId: 'agora-live-streaming-10',
    storageBucket: 'agora-live-streaming-10.firebasestorage.app',
    iosBundleId: 'com.example.agoraLiveStream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAHwXEGUKachQoVNnjHAtv2lFgoNJEMmc',
    appId: '1:186129183743:web:d96377e64132ee07df6dca',
    messagingSenderId: '186129183743',
    projectId: 'agora-live-streaming-10',
    authDomain: 'agora-live-streaming-10.firebaseapp.com',
    storageBucket: 'agora-live-streaming-10.firebasestorage.app',
  );
}
